# Generated by Django 5.1.3 on 2024-11-13 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.IntegerField(max_length=25, null=True)),
                ('last_name', models.IntegerField(max_length=25, null=True)),
                ('email', models.IntegerField(max_length=25, null=True)),
                ('mobile', models.IntegerField(max_length=10, null=True)),
                ('place', models.IntegerField(max_length=25, null=True)),
                ('image', models.ImageField(null=True, upload_to='agents/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
