# Generated by Django 5.1.3 on 2024-11-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='campaigns/')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agent')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
