# Generated by Django 5.1.3 on 2024-11-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.agent'),
        ),
    ]
