# Generated by Django 5.1.3 on 2024-11-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
