# Generated by Django 5.1.3 on 2024-11-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_campaign_campaign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='agent',
        ),
        migrations.AddField(
            model_name='campaign',
            name='agents',
            field=models.ManyToManyField(to='app.agent'),
        ),
    ]
