# Generated by Django 5.1.3 on 2024-11-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_campaignagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.campaign'),
        ),
    ]
