# Generated by Django 5.1.3 on 2024-11-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_client_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='campaign',
        ),
    ]
